### ISSUE TITLE
0.6 release not released

### ISSUE THREAD

**Issue by mboelen** [mschwager/gitem#5]
We recently added your project to our website: https://linuxsecurity.expert/tools/gitem/

While just looking at the latest version, I saw that the 0.6.0 version was not created as a release. Might be good to bump it up, so other tools can detect the latest version.

Keep up the good work :)

**Comment by mschwager** [comment]
Good catch!

Just added it: https://github.com/mschwager/gitem/releases/tag/0.6.0

Thanks for the heads up!
