### ISSUE TITLE
ValueError: anon must be one of [1, 'true']

### ISSUE THREAD

**Issue by dkasak** [mschwager/gitem#6]
When running the example `gitem repository facebook react`, I get the following error:

```
Traceback (most recent call last):
  File "lib/gitem/__main__.py", line 301, in <module>
    main()
  File "lib/gitem/__main__.py", line 280, in main
    dispatch[args.command](ghapi, **vars(args))
  File "lib/gitem/__main__.py", line 110, in repository
    repository
  File "/home/dkasak/code/projects/gitem/lib/gitem/analytics.py", line 122, in get_repository_contributors
    repository
  File "/home/dkasak/code/projects/gitem/lib/gitem/api.py", line 280, in get_repository_contributors
    raise ValueError("anon must be one of {}".format(anon_values))
ValueError: anon must be one of [1, 'true']
```

Looking at the commit history, this bit of 72da801 looks wrong:

```diff
@@ -265,7 +275,9 @@ class Api(object):
 
         https://developer.github.com/v3/repos/#list-contributors
         """
-        assert anon in [1, "true", None]
+        anon_values = [1, "true"]
+        if anon not in anon_values and type is not None:
+            raise ValueError("anon must be one of {}".format(anon_values))
```

There's no `type` variable in that function and `None` is dropped in the transition from the assert to the new code.

**Comment by mschwager** [comment]
Good catch! Thank you! This should be fixed in https://github.com/mschwager/gitem/commit/87954d6663cd2a8704bbc972192307ba139b0dcb

I think the bigger takeaway is: this is why you don't use builtin names as variable names :)

`type is not None` will always return true because `type` is a builtin function, and it will never be `None`.

**Comment by dkasak** [comment]
@mschwager My pleasure.

> I think the bigger takeaway is: this is why you don't use builtin names as variable names :)

I was just going to mention this. I think you're onto something here. ;)
