### ISSUE TITLE
request with oauth

### ISSUE THREAD

**Issue by vulnz** [mschwager/gitem#7]
Hello man! can you please tell me how to add oauth into your program?
I have "
gitem.api.ApiCallException: 401: {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
"
Please give me an example of how to send requests with oauth

**Comment by mschwager** [comment]
Hi @vulnz! You should be able to use a personal oath access token by using the `-o` flag.

E.g.

```
gitem -o <oath-token> ...
```
