### ISSUE TITLE
How get token to gitem

### ISSUE THREAD

**Issue by Cheban1996** [mschwager/gitem#8]
Please, talk me how get token to gitem

**Comment by mschwager** [comment]
Hey @Cheban1996!

I assume you're talking about an OAuth token, similar to https://github.com/mschwager/gitem/issues/7?

> You should be able to use a personal oauth access token by using the -o flag.
> 
> E.g.
> 
> `gitem -o <oath-token> ...`

For instructions on creating a token, you can look at Github's documentation on [creating a personal access token for the command line](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/).
