### ISSUE TITLE
exit in format json

### ISSUE THREAD

**Issue by tXambe** [mschwager/gitem#9]
Hello,

how can I get the output of the command in json format because with the -t modifier gives error

--------------------------------------------------------------------------------------------------
gitem organization microsoft -t
usage: gitem [-h] [-o OAUTH2_TOKEN] [-v] [-p PROCESSES] [-t {stdout,json}]
             {organization,repository,user} ...
gitem: error: unrecognized arguments: -t

gitem organization microsoft -t json
usage: gitem [-h] [-o OAUTH2_TOKEN] [-v] [-p PROCESSES] [-t {stdout,json}]
             {organization,repository,user} ...
gitem: error: unrecognized arguments: -t json

Thanks and a greeting

**Comment by mschwager** [comment]
Hi there!

The `-t` argument has to come before `organization`, like so:

```
$ gitem -t json organization microsoft
```

Let me know if you have any other questions :+1:
